apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-nfs-provisioner
  namespace: default
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntu
  name: ubuntu-test-nfs
  namespace: default
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    resources: {}
    command: ["sleep", "3600"]
    volumeMounts:
      - mountPath: /nfs
        name: nfs-vol
  volumes:
    - name: nfs-vol
      persistentVolumeClaim:
        claimName: test-nfs-provisioner
